__default__ :
        job-name      : "{rule}"
        output        : "logs/{rule}/{wildcards}.out"
        ntasks        : 1
        cpus-per-task : 1
        mem           : "200M"
        time          : "00-00:05:00"
        account       : "my_account"
        partition     : "my_partition"

fastq_to_gz:
        cpus-per-task : 12
        time          : "00-01:00:00"

nanoplot:
        cpus-per-task : 12
        time          : "00-12:00:00"

remove_control_DNA:
        cpus-per-task : 12
        time          : "00-12:00:00"

quality_filtering:
        cpus-per-task : 12
        time : "00-03:00:00"

filtered_trimmed_nanoplot:
        cpus-per-task : 12
        time : "00-12:00:00"

minimap2_plastid:
        cpus-per-task : 12
        time : "00-03:00:00"
        mem : "20G"

map_long_reads_to_OsJap_mito:
        cpus-per-task : 12
        time : "00-03:00:00"

samtools_minimap2_plastid:
        cpus-per-task : 12
        time : "00-03:00:00"

extract_only_mapping_mito_reads:
        cpus-per-task : 12
        time : "00-03:00:00"

extract_plastid_read_names:
        cpus-per-task : 2
        time : "00-00:10:00"

extract_mito_read_names:
        cpus-per-task : 2
        time : "00-00:10:00"

sort_unique_mapped_read_names:
        cpus-per-task : 12
        time : "00-00:50:00"

sort_unique_mito_mapped_read_names:
        cpus-per-task : 12
        time : "00-00:50:00"

pull_unique_reads:
        cpus-per-task : 12
        time : "00-00:30:00"

pull_unique_mito_reads:
        cpus-per-task : 12
        time : "00-00:30:00"

plastid_reads_nanoplot:
        cpus-per-task : 12
        time : "00-12:00:00"

sort_chloro_fastq_by_read_length:
        cpus-per-task : 12
        time : "00-00:30:00"

sort_mito_fastq_by_read_length:
        cpus-per-task : 12
        time : "00-00:30:00"

list_longest_plastid_reads_x_coverage:
        cpus-per-task : 2
        time : "00-00:10:00"

create_list_for_filtering_plastid_reads:
        cpus-per-task : 2
        time : "00-00:50:00"

subsample_reads_for_x_coverage:
        cpus-per-task : 2
        time : "00-00:10:00"

remove_chloro_long_reads_from_mito_reads:
        cpus-per-task : 12
        time : "00-00:45:00"

filter_mito_long_reads:
        cpus-per-task : 6
        time : "00-12:00:00"

subset_reads_for_x_coverage:
        cpus-per-task : 6
        time : "00-00:30:00"

raw_flye_chloro_assembly:
        cpus-per-task : 20
        time : "00-05:00:00"
        mem : "20G"

raw_flye_mito_assembly:
        cpus-per-task : 12
        time : "00-15:00:00"

map_short_reads_to_plastid_genomes:
        cpus-per-task : 16
        time : "00-05:00:00"

flye_chloroplast_assembly:
        cpus-per-task : 12
        time : "00-02:00:00"

flye_mito_assembly:
        cpus-per-task : 12
        time : "00-02:00:00"

map_short_reads_to_plastid_ref:
        cpus-per-task : 12
        time : "00-03:00:00"

pull_reads_mapped_to_plastid:
        cpus-per-task: 12
        time : "00-03:00:00"

extract_plastid_short_read_names:
        cpus-per-task : 12
        time : "00-03:00:00"

sort_unique_plastid_short_reads:
        cpus-per-task : 12
        time : "00-03:00:00"

add_at_to_each_read_name:
        cpus-per-task : 1
        time : "00-00:10:00"

pull_unique_plastid_short_reads:
        cpus-per-task : 12
        time : "00-03:00:00"

remove_chloro_short_reads_from_mito:
        cpus-per-task : 12
        time : "00-01:00:00"

filter_mito_short_reads:
        cpus-per-task : 12
        time : "00-01:00:00"

raw_unicycler_mito_assembly:
        cpus-per-task : 20
        time : "03-00:00:00"
        mem : "200G"
        partition : "highmem"

filter_plastid_reads:
        cpus-per-task : 1
        time : "00-01:00:00"
        mem : "2G"

filter_reads_below_10kbp:
        cpus-per-task : 1
        time : "00-10:00:00"
        mem : "2G"

canu_nuclear_genome_assembly:
        time: "00-72:00:00"
        mem: "1G"

# Override the above defaults with job specific values
#bwa_mem :
#        cpus-per-task : 16
#        mem           : "10000M"
#        time          : "00-01:00:00"

# Job specific resource requirements can be passed from the rule, in the Snakefile, via the "resources" keyword
#bwa_mem :
#        cpus-per-task : 4
#        mem           : "{resources.mem_mb}M"
#        time          : "00-{resources.time_hrs}:00:00"
