NCBI_reference_accession: NC_031333.1  #NC_035996.1
my_Email: aaron.phillips@adelaide.edu.au

fast_file: fastq # fastq/fasta
compression: .gz # .gz or blank

randSeed: 100
numberReads: 1500
flyeParameter: --nano-raw #‘--nano-raw’ for ONT reads base-called prior to the release of Guppy5+, ‘--nano-corr’ for corrected ONT reads, or ‘--nano-hq’ for high quality ONT reads that have been base-called with Guppy5+; for PacBio CLR reads use ‘--pacbio-raw’ for regular CLR reads, or ‘--pacbio-corr’ for corrected CLR reads, or PacBio HiFi reads use ‘--pacbio-hifi’

minimap2Parameter: map-ont #'map-pb' for PacBio CLR reads or 'map-ont' for ONT long reads or 'map-hifi' for PacBio HiFi reads

chloroplastSize: 135000 #rough estimate
chloroplastSizePC: 0.85
chloroplastIdentityPC: 0.85

cpus: 6
