NCBI_reference_accession: NC_014063.1  #NC_031333.1  #NC_035996.1
my_Email: aaron.phillips@adelaide.edu.au

fast_file: fastq # fastq/fasta
compression: .gz # .gz or blank

randSeed: 100
numberReads: 1500
flyeParameter: --nano-raw 
    # --nano-raw    = ONT reads base-called prior to the release of Guppy5+
    # --nano-corr   = corrected ONT reads
    # --nano-hq     = high quality ONT reads that have been base-called with Guppy5+
    # --pacbio-raw  = PacBio CLR reads
    # --pacbio-corr = corrected CLR reads
    #--pacbio-hifi  = PacBio HiFi reads

minimap2Parameter: map-ont
    # map-pb   = PacBio CLR reads
    # map-ont  = ONT long reads 
    # map-hifi = PacBio HiFi reads


chloroplastSize: 135000  # estimate of chloroplast genome size

# Chlorplast QC check parameters
chloroplastSizePC: 0.85     # If assembled genome >(chloroplastSize*chloroplastSizePC), will not pass.
chloroplastIdentityPC: 0.85 # If assembled genome > this % the same as reference, will not pass

cpus: 6 # Max CPUs to use in a job.
