NCBI_reference_accession: NC_029243.1 #NC_004543.1 #NC_034777.1 #NC_023533.1 #NC_022393.1 #NC_006290.1 #NC_013843.1 #NC_028069.1 #NC_015891.1 #NC_023216.1 #NC_003119.1 #NC_008289.1 #NC_027223.1 #NC_031855.1 #NC_034696.1 #NC_014063.1 #NC_012097.1 #NC_005353.1 #NC_008155.1
my_Email: aaron.phillips@adelaide.edu.au

fast_file: fastq # fastq/fasta/fastq.gz/fasta.gz

randSeed: 100
numberReads: 3000
readMinLength: 5000
readMaxLength: 100000 # longest read that will be used for assembly.
                    # We dont want reads that are bigger than the expected chloroplast size.
                    
flyeParameter: --nano-raw 
    # --nano-raw    = ONT reads base-called prior to the release of Guppy5+
    # --nano-corr   = corrected ONT reads
    # --nano-hq     = high quality ONT reads that have been base-called with Guppy5+
    # --pacbio-raw  = PacBio CLR reads
    # --pacbio-corr = corrected CLR reads
    #--pacbio-hifi  = PacBio HiFi reads

minimap2Parameter: map-ont
    # map-pb   = PacBio CLR reads
    # map-ont  = ONT long reads 
    # map-hifi = PacBio HiFi reads


chloroplastSize: 135000  # estimate of chloroplast genome size

# Chlorplast QC check parameters
chloroplastSizePC: 0.85     # If assembled genome <(chloroplastSize*chloroplastSizePC), will not pass.
chloroplastIdentityPC: 0.85 # If the identity (measured by DNADiff) of assembled genome to reference genome <chloroplastIdentityPC, will not pass

cpus: 6 # Max CPUs to use in a job.
