channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - unzip=6.0
 - pigz=2.3.4
 - samtools=1.9
 - htslib=1.9
 - nanoplot=1.28.0
 - seqtk=1.3
 - bioawk=1.0
 - racon=1.4.11
 - minimap2=2.17
 - unicycler=0.4.8
 - bbmap=38.86
