cluster:
  "profiles/slurm/submit -J {cluster.job-name} -t {cluster.time} -p {cluster.partition} -A {cluster.account} -n {cluster.ntasks} -c {cluster.cpus-per-task} -m {cluster.mem} -o {cluster.output} -g {cluster.gres} -d '{dependencies}' -N '{cluster.nodes}'"
cluster-status:
  "status"
jobscript:
  "jobscript"
restart-times:
  0
latency-wait:
  30
max-jobs-per-second:
  5
max-status-checks-per-second:
  5
local-cores:
  4
jobs:
  100
cluster-config:
 - "cluster-configs/slurm.yaml"
keep-going:
  true
use-conda:
  true
conda-frontend:
  "mamba"
